server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/insurance
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  session:
    timeout: 30m
  messages:
    encoding: UTF-8
  security:
    user:
      name: admin
      password: password

logging:
  level:
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    enabled: true

  logging:
  level:
    org.hibernate.SQL: DEBUG