server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/insurance
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  # Configuration de la gestion des sessions
  session:
    timeout: 30m  # Durée de vie de la session (ici 30 minutes)

  # Gestion de l'encoding
  messages:
    encoding: UTF-8  # Assurez-vous que les messages sont bien encodés en UTF-8

logging:
  level:
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE


springsecurity:
  user:
    name: admin
    password: password
  oauth2:
    client:
      registration:
        google:
          client-id: your-client-id
          client-secret: your-client-secret

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    enabled: true
