server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/insurance
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


  session:
    timeout: 30m


  messages:
    encoding:

logging:
  level:
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE


springsecurity:
  user:
    name: admin
    password: password
  oauth2:
    client:
      registration:
        google:
          client-id: your-client-id
          client-secret: your-client-secret

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    enabled: true

security:
  session:
    create-session: always